// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
)

// User defines model for User.
type User struct {
	Email string `json:"email,omitempty"`
	Id    int64  `json:"id,omitempty"`
}

// PostApiTestJSONRequestBody defines body for PostApiTest for application/json ContentType.
type PostApiTestJSONRequestBody = User

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/test)
	GetApiTest(c *fiber.Ctx) error

	// (POST /api/test)
	PostApiTest(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetApiTest operation middleware
func (siw *ServerInterfaceWrapper) GetApiTest(c *fiber.Ctx) error {

	return siw.Handler.GetApiTest(c)
}

// PostApiTest operation middleware
func (siw *ServerInterfaceWrapper) PostApiTest(c *fiber.Ctx) error {

	return siw.Handler.PostApiTest(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/test", wrapper.GetApiTest)

	router.Post(options.BaseURL+"/api/test", wrapper.PostApiTest)

}

type GetApiTestRequestObject struct {
}

type GetApiTestResponseObject interface {
	VisitGetApiTestResponse(ctx *fiber.Ctx) error
}

type GetApiTest200JSONResponse User

func (response GetApiTest200JSONResponse) VisitGetApiTestResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PostApiTestRequestObject struct {
	Body *PostApiTestJSONRequestBody
}

type PostApiTestResponseObject interface {
	VisitPostApiTestResponse(ctx *fiber.Ctx) error
}

type PostApiTest200JSONResponse User

func (response PostApiTest200JSONResponse) VisitPostApiTestResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/test)
	GetApiTest(ctx context.Context, request GetApiTestRequestObject) (GetApiTestResponseObject, error)

	// (POST /api/test)
	PostApiTest(ctx context.Context, request PostApiTestRequestObject) (PostApiTestResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiTest operation middleware
func (sh *strictHandler) GetApiTest(ctx *fiber.Ctx) error {
	var request GetApiTestRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiTest(ctx.UserContext(), request.(GetApiTestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiTest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetApiTestResponseObject); ok {
		if err := validResponse.VisitGetApiTestResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostApiTest operation middleware
func (sh *strictHandler) PostApiTest(ctx *fiber.Ctx) error {
	var request PostApiTestRequestObject

	var body PostApiTestJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiTest(ctx.UserContext(), request.(PostApiTestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiTest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PostApiTestResponseObject); ok {
		if err := validResponse.VisitPostApiTestResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SRTW/UQAyG/wp64ZhssnxU1ZyAC+LGAU5VD9PEm7gkY3fGQa1W+e/Iw0dViQMHJE72",
	"2GP7sd8zBllVEiUrCGeUYaY1VvdLoexWsyhlY6pRWiMv1bmPqy6EgDTNHG9Ijhf9m7eT5w+DrGhgD+r5",
	"YpnThAb37SStB9vylbUVNZYUl1aFk/kwyxvtDXh8MuDY4CR5jYYATnbx+rG1102U/7r33iDT3caZRoQr",
	"qHNd/+4mN7c0GHb/xukkTmFsdcnPVOyZRGU0+Ea5sCQEHA/9ocfeQJSSJwNe1VADjTbXi3VRuTMq5o+J",
	"qvGLRif8OCLgA9k7ZZ8A5ysqqfy49su+dzNIMkq1MqouPNTa7rY4xC/R3HuR6YSA592jqt1PSbuqZ91t",
	"pDJkrhdCQEWrcZXyB7pPUp7g3W1U7L2MD/+cbP+P23umUHZpEa7O2PKCgNlMQ9ctMsRllmLhsr/ssV/v",
	"3wMAAP//ruy+7DgDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
